Feat/staking usd
elysia-dev/elyfi-web pull request #164
Opened 2022-04-27 05:41 UTC by hyunoh-modori

우선 useTokenUsdAmount.ts를 호출해서 ELFI, LP Eth, LP Dai 값을 불러옵니다.
그리고 staking 페이지들의 index에서 토큰 가격을 가져온 다음, useCurrentStakingAmount, useCurrentRewardAmount에 각각 넘겨줍니다.
해당 hooks에서는 로딩 인디케이터를 보여주다가, 로딩이 끝나면 값을 계산해서 실시간으로 보여줍니다.

작업된 기능의 적용 범위는 ELFI, LP Staking 뿐이며, 그 외 다른 기능은 없습니다

---
<img width="449" alt="스크린샷 2022-04-27 오후 2 37 34" src="https://user-images.githubusercontent.com/59865307/165448239-a44a87f4-a72e-4287-9044-e92f60570fbf.png">
LP staking의 이 부분은 아직 해당 브랜치가 리팩토링 코드 적용 전이라 data[0]을 그대로 사용했습니다. 리팩토링 할 때 같이 작업하겠습니다..!

2022-04-27 06:49 UTC, donguks requested changes

2022-04-27 06:49 UTC, donguks commented on src/components/Staking/hooks/useCurrentRewardAmount.tsx
> +const useCurrentRewardAmount = (
다른 hooks를 보면 알겠지만, 사용하는 상태값들을 리턴하도록 되어있습니다. 여기서는 컴포넌트를 리턴하는 함수를 리턴하도록 설계되었는데, 다른 Hooks들과 성격이 다른 것 같습니다. 또한 조건문에 따라 컴포넌트를 return할뿐인데 hooks가 아니라 component로 만들어도 무방할 것 같습니다. `useMemo`도 사용하지 않아도 될것 같은데 무엇을 의도하신건지 궁금합니다.

2022-04-27 06:49 UTC, donguks commented on src/components/Staking/hooks/useCurrentStakingAmount.tsx
> +const useCurrentStakingAmount = (
여기도 마찬가지로 컴포넌트로 만드는게 더 나을 것 같고, 리턴하는게 컴포넌트 또는 문자열인데 모두 컴포넌트로 통일하는게 더 나을것 같아요!

2022-04-27 06:49 UTC, donguks commented on src/hooks/useTokenUsdAmount.ts
> +const useTokenUsdAmount = () => {
`useTokenUsdAdmout` 보다 `useLpPrice`정도가 더 좋을 것 같은데 어떤가요?
useTokenUsdAdmout의 이름은 토큰의 usd 가치를 리턴할 것 같은데, 실제 구현하신건 LP의 가격을 리턴하도록 만드신것 같아서요!

2022-04-27 06:49 UTC, donguks commented on src/hooks/useTokenUsdAmount.ts
> +  const [tokenUsdAmount, setTokenUsdAmount] = useState({
price, loading, error 모두 하나의 state로 관리해도 괜찮을것 같아요!

2022-04-27 14:16 UTC, hyunoh-modori commented
모든 피드백을 반영했습니다!
state를 정리한 뒤 parameter를 재설정 했고, priceData.elfiPrice 도 따로 불러오도록 했습니다.
hooks는 원래 정말 값만 전달해주려 했는데 스켈레톤이랑 count가 들어가면서 이도저도 아니게 변해버렸네요 ㅠㅠ jsx.element를 리턴하도록 재설계 했습니다!

2022-04-28 09:56 UTC, donguks approved these changes
Component 형식으로 호출하도록 변경 후 머지해주시면 됩니다!

2022-04-28 09:56 UTC, donguks commented on src/components/LpStaking/index.tsx
> +  const daiRewardTokenAmount = CurrentRewardAmount(
coponent로 만들었으면, 요렇게 변수로 하지 않고, return()안에서 컴포넌트로 넣어주면 더 좋을것 같습니다!

2022-05-03 01:38 UTC, donguks commented on src/hooks/useLpPrice.ts
> +    loadAmountData();
loadAmountData는 비동기함수도 아니고, 재활용도 하지 않으니 선언하지 않고 바로 useEffect안에서 해당 논리를 실행해도 괜찮을것 같습니다!

2022-05-03 01:40 UTC, donguks approved these changes

2022-05-03 02:03 UTC, merged