Feature/wallet connect
elysia-dev/elyfi-web pull request #75
Opened 2022-02-17 09:14 UTC by JUNG-gyucheol

- wallect Connect 추가
- 일반 브라우저에서는 wallet connect 로만 연결가능
- 지갑에서 브라우저를 지원하는 경우 wallet connect 와 browser wallet 으로 모두 사용가능
- 지갑 연결 후 웹에서 네트워크를 변경하더라도 유저정보를 제외한 나머지 정보는 그대로 보여줌

2022-02-21 03:11 UTC, donguks requested changes
Wallet Connect 구현 잘보았습니다. 네트워크 변경이슈를 적절하게 해결하셨군요!

코드 변경사항 중 코드 포맷팅 관련 내용이 더 많은 것 같은데, 기존 main 브랜치 모든 파일들 포맷을 다 동일하게 해 준 뒤 작업하는게 더 편할 것 같습니다. 어디가 변경점인지 쉽게 보이지 않군요 ㅜㅜ 다음에 PR올리실때 File changed 한번 확인하셔서 변경한 내용들이 의도에 맞는지 점검해주시면 좋을것 같습니다.
몇가지 사소한 것들 수정하고, 사내 기능 테스트 후에 배포하면 좋을것 같습니다. 일정을 잡아보시죠!

2022-02-21 03:11 UTC, donguks commented on src/components/SelectWalletModal.tsx
> +  const walletConnectProvider = walletConnectConnector();
const global: WindowWithEthereum = window as WindowWithEthereum;
const walletConnectProvider = walletConnectConnector();

두 변수 모두 SelectWalletModal 안에 선언하지 않아도 될것 같습니다.

2022-02-21 03:11 UTC, donguks commented on src/components/SelectWalletModal.tsx
> +  const isMoblie =
isMobile 이미 있는것 써보면 좋을것 같습니다.

2022-02-21 03:11 UTC, donguks commented on src/components/TableBodyEventReward.tsx
> +                  isWrongMainnet ? (
unsupportedChainid와 isWrongMainnet의 차이는 무엇일까요? 이렇게 조건문을 추가해야하는 이유가 궁금합니다~

2022-02-21 03:11 UTC, donguks commented on src/core/connectors/WalletConnector.ts
> +/* eslint-disable import/no-extraneous-dependencies */
이 클래스가 사용되고 있는 곳이 있을까요?
PR 코드를 읽으면 확인한건, web3-react와 @web3-react/walletconnect-connector 두개로 구현한것 같아서요!

2022-02-21 03:11 UTC, donguks commented on src/containers/Dashboard.tsx
> +                  isWrongMainnet
onClick이랑, setIncentiveModalVisible가 점점 복잡해지네요! 혹시 해결할 수 있는 방법이 있을까요?

2022-02-22 15:59 UTC, JUNG-gyucheol commented on src/core/connectors/WalletConnector.ts
> +/* eslint-disable import/no-extraneous-dependencies */
activate() 인자로 walletConnectProvider 가 맞지 않아서 WalletConnectConnector 클래스에서 AbstractConnector 를 상속받아서 커스텀 했습니다.
wallect connect 를 연결할 때마다 사용하고 있습니다.

2022-02-23 01:39 UTC, JUNG-gyucheol commented on src/components/TableBodyEventReward.tsx
> +                  isWrongMainnet ? (
- unsupportedChainid 는 Chrome 확장자로 연결 했을 때 네트워크가 잘못된 경우
- isWrongMainnet 는 wallet connect 또는 모바일로 메타마크스 브라우저 이용시 네트워크가 잘못된 경우

2022-02-23 04:20 UTC, JUNG-gyucheol commented on src/components/SelectWalletModal.tsx
> +  const walletConnectProvider = walletConnectConnector();
const walletConnectProvider = walletConnectConnector();
 이 부분 wallet connect 연결 할 때 취소를 하고 다시 연결하려고 하니 연결이 안되네요.
 다시 안에서 선언했습니다.

2022-02-23 05:29 UTC, donguks commented on src/components/SelectWalletModal.tsx
> +  const walletConnectProvider = walletConnectConnector();
아니 그런일이.. 그렇다면 괜찮습니다. 대신 코멘트 남겨주세요~

2022-02-24 07:41 UTC, donguks approved these changes
고생하셨습니다!
#53 이 PR이 머지된 후에 들어가는게 좋을것 같아요. 사용성 측면에서, wallet connect는 눌렀을때 화면에 아무런 반응이 없으며 매우 어색한데, #53 에서 이를 해결했습니다. 
conflict 해결 먼저 해주시면 됩니다!

2022-03-03 08:04 UTC, merged