Feature/bsc staking
elysia-dev/elyfi-web pull request #79
Opened 2022-02-22 08:57 UTC by JUNG-gyucheol

- 보상 플랜페이지 리팩토링 및 ELFI 스테이킹(BSC) 구현 
- 스테이킹 페이이 리팩토링 및 ELFI 스테이킹(BSC) 구현

테스트 해봐야 되는데 아직 BSC 스테이킹풀 주소가 없어서 못했습니다.
컴포넌트들이 많이 변경되어서 EL, ELFI 스테이킹 테스트도 필요할 것 같습니다.

2022-02-24 06:11 UTC, donguks requested changes
이전 코드 리팩토링할게 좀 있지만, 이번 작업에 해당하는 것들은 아니니 다음에 작업하면 좋겠군요!
사소한 몇가지 수정 및 테스트 후에 배포하도록 하죠!

2022-02-24 06:11 UTC, donguks commented on src/hooks/useERC20.ts
> +            ? process.env.REACT_APP_JSON_RPC_BSC
REACT_APP_JSON_RPC_BSC 이건 prod.json이나 test.json으로 관리해도될것 같습니다. 
REACT_APP_JSON_RPC는 infura를 사용해야해서 숨겨야하는 값인데, REACT_APP_JSON_RPC_BSC는 bsc에서 공짜로 지원해주는 api이기 때문입니다.

2022-02-24 06:11 UTC, donguks commented on src/hooks/useCalcReward.ts
> +    beforeStakingPool: state
지금보니 엄청 복잡하네요... 더 좋은 방법이 있겠죠?

2022-02-25 09:50 UTC, hyunoh-modori approved these changes

2022-02-25 09:52 UTC, donguks approved these changes

2022-02-25 09:53 UTC, merged